import { ProjectData, FrameData, FrameType } from '../types';
import { save } from '@tauri-apps/plugin-dialog';
import { writeTextFile } from '@tauri-apps/plugin-fs';

/**
 * 导出项目为 FDF 格式（魔兽3 UI 文件格式）
 */
export async function exportToFDF(project: ProjectData): Promise<void> {
  try {
    // 打开保存对话框
    const path = await save({
      filters: [{
        name: 'Frame Definition File',
        extensions: ['fdf']
      }],
      defaultPath: 'ui-design.fdf'
    });

    if (!path) return; // 用户取消

    // 生成 FDF 内容
    const fdfContent = generateFDFContent(project);

    // 写入文件
    await writeTextFile(path, fdfContent);

    alert('导出 FDF 成功！');
  } catch (error) {
    console.error('导出 FDF 失败:', error);
    alert(`导出失败: ${error}`);
  }
}

/**
 * 导出项目为 JSON 格式
 */
export async function exportToJSON(project: ProjectData): Promise<void> {
  try {
    const path = await save({
      filters: [{
        name: 'JSON File',
        extensions: ['json']
      }],
      defaultPath: 'ui-design.json'
    });

    if (!path) return;

    const jsonContent = JSON.stringify(project, null, 2);
    await writeTextFile(path, jsonContent);

    alert('导出 JSON 成功！');
  } catch (error) {
    console.error('导出 JSON 失败:', error);
    alert(`导出失败: ${error}`);
  }
}

/**
 * 生成 FDF 文件内容
 */
function generateFDFContent(project: ProjectData): string {
  const lines: string[] = [];

  // 添加文件头注释
  lines.push('// Generated by WC3 UI Designer');
  lines.push(`// Date: ${new Date().toLocaleString()}`);
  lines.push(`// Origin Mode: ${project.originMode}`);
  lines.push('');

  // 包含必要的文件
  lines.push('IncludeFile "UI\\FrameDef\\UI\\EscMenuTemplates.fdf",');
  lines.push('');

  // 递归生成所有控件的 FDF 代码
  for (const frameId of project.rootFrameIds) {
    generateFrameFDF(project.frames[frameId], project.frames, lines, 0, project);
  }

  return lines.join('\n');
}

/**
 * 递归生成单个控件的 FDF 代码
 */
function generateFrameFDF(
  frame: FrameData,
  allFrames: Record<string, FrameData>,
  lines: string[],
  indent: number,
  project: ProjectData
): void {
  const indentStr = '    '.repeat(indent);

  // Frame 定义开始
  lines.push(`${indentStr}Frame "${getFrameTypeName(frame.type)}" "${frame.name}" {`);

  // 如果有父控件，设置 UseActiveContext
  if (frame.parentId) {
    lines.push(`${indentStr}    UseActiveContext TRUE,`);
  }

  // 设置尺寸
  lines.push(`${indentStr}    Width ${frame.width},`);
  lines.push(`${indentStr}    Height ${frame.height},`);

  // 设置锚点
  if (frame.anchors && frame.anchors.length > 0) {
    for (const anchor of frame.anchors) {
      const anchorLine = generateAnchorFDF(anchor, frame, allFrames, indentStr, project);
      if (anchorLine) {
        lines.push(anchorLine);
      }
    }
  } else {
    // 如果没有锚点，使用默认位置
    lines.push(`${indentStr}    SetPoint TOPLEFT, "${getParentName(frame, allFrames, project)}", TOPLEFT, ${frame.x}, ${-frame.y},`);
  }

  // 根据类型添加特定属性
  switch (frame.type) {
    case FrameType.BACKDROP:
      if (frame.wc3Texture || frame.diskTexture) {
        const texture = frame.wc3Texture || frame.diskTexture;
        lines.push(`${indentStr}    BackdropBackground "${texture}",`);
        lines.push(`${indentStr}    BackdropCornerFlags "UL|UR|BL|BR|T|L|B|R",`);
      }
      break;

    case FrameType.TEXT_FRAME:
      if (frame.text) {
        lines.push(`${indentStr}    Text "${frame.text}",`);
      }
      if (frame.horAlign) {
        const fontSize = frame.textScale || 0.012;
        lines.push(`${indentStr}    FrameFont "MasterFont", ${fontSize}, "",`);
      }
      break;

    case FrameType.BUTTON:
    case FrameType.BROWSER_BUTTON:
    case FrameType.SCRIPT_DIALOG_BUTTON:
      if (frame.text) {
        lines.push(`${indentStr}    ButtonText "${frame.text}",`);
      }
      break;

    case FrameType.EDITBOX:
    case FrameType.TEXTAREA:
      if (frame.text) {
        lines.push(`${indentStr}    EditTextFrame "${frame.text}",`);
      }
      break;
  }

  // 递归处理子控件
  if (frame.children && frame.children.length > 0) {
    lines.push('');
    for (const childId of frame.children) {
      const child = allFrames[childId];
      if (child) {
        generateFrameFDF(child, allFrames, lines, indent + 1, project);
      }
    }
  }

  // Frame 定义结束
  lines.push(`${indentStr}}`);
  lines.push('');
}

/**
 * 生成锚点的 FDF 代码
 */
function generateAnchorFDF(
  anchor: any,
  frame: FrameData,
  allFrames: Record<string, FrameData>,
  indentStr: string,
  project: ProjectData
): string | null {
  const point = anchor.point || 'TOPLEFT';
  const relativePoint = anchor.relativePoint || 'TOPLEFT';
  const x = anchor.x || 0;
  const y = anchor.y || 0;

  // 获取相对控件名称
  let relativeTo = getParentName(frame, allFrames, project);
  if (anchor.relativeTo) {
    const relativeFrame = allFrames[anchor.relativeTo];
    if (relativeFrame) {
      relativeTo = relativeFrame.name;
    }
  }

  return `${indentStr}    SetPoint ${point}, "${relativeTo}", ${relativePoint}, ${x}, ${-y},`;
}

/**
 * 获取父控件名称
 */
function getParentName(frame: FrameData, allFrames: Record<string, FrameData>, project?: ProjectData): string {
  if (!frame.parentId) {
    // 根节点的父控件根据 originMode 决定
    if (project) {
      switch (project.originMode) {
        case 'gameui': return 'GameUI';
        case 'worldframe': return 'WorldFrameWar3';
        case 'consoleui': return 'ConsoleUI';
        default: return 'ConsoleUI';
      }
    }
    return 'ConsoleUI';
  }

  const parent = allFrames[frame.parentId];
  return parent ? parent.name : 'ConsoleUI';
}

/**
 * 获取 Frame 类型的 FDF 名称
 */
function getFrameTypeName(type: FrameType): string {
  switch (type) {
    case FrameType.BACKDROP: return 'BACKDROP';
    case FrameType.BUTTON: return 'BUTTON';
    case FrameType.BROWSER_BUTTON: return 'BUTTON';
    case FrameType.SCRIPT_DIALOG_BUTTON: return 'BUTTON';
    case FrameType.TEXT_FRAME: return 'TEXT';
    case FrameType.CHECKBOX: return 'CHECKBOX';
    case FrameType.HORIZONTAL_BAR: return 'SLIDER';
    case FrameType.TEXTAREA: return 'EDITBOX';
    case FrameType.EDITBOX: return 'EDITBOX';
    case FrameType.SLIDER: return 'SLIDER';
    default: return 'FRAME';
  }
}

/**
 * 导出为 PNG 预览图
 */
export async function exportToPNG(canvasElement: HTMLCanvasElement | null): Promise<void> {
  if (!canvasElement) {
    alert('无法获取画布元素');
    return;
  }

  try {
    const path = await save({
      filters: [{
        name: 'PNG Image',
        extensions: ['png']
      }],
      defaultPath: 'ui-preview.png'
    });

    if (!path) return;

    // 将 canvas 转换为 data URL
    const dataUrl = canvasElement.toDataURL('image/png');
    
    // 直接使用浏览器下载（Tauri 环境下的简化方案）
    const link = document.createElement('a');
    link.download = path.split(/[\\/]/).pop() || 'ui-preview.png';
    link.href = dataUrl;
    link.click();

    alert('导出 PNG 成功！');
  } catch (error) {
    console.error('导出 PNG 失败:', error);
    alert(`导出失败: ${error}`);
  }
}
